database = {
    "animal": [],
    "aves": [],
    "amphibian": [],
    "customer": [],
    "arthropod": [],
    "facility": [],
    "habitat": [],
    "location": [],
    "mammal": [],
    "pisces": [],
    "sales": [],
    "shop": [],
    "staff": [],
    "product": [],
    "porductType": [],
    "reptiles": [],
    "decoration": [],
}